package com.example.androidnotebook;

import android.content.Context;

import com.example.androidnotebook.dao.NoteDao;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutorService;
// Removed AtomicLong as ID is generated by Room

public class NoteManager {
    private static NoteManager instance;
    private final NoteDao noteDao;
    private final ExecutorService databaseWriteExecutor;

    // Private constructor for singleton
    private NoteManager(Context context) {
        AppDatabase database = AppDatabase.getDatabase(context.getApplicationContext());
        this.noteDao = database.noteDao();
        this.databaseWriteExecutor = AppDatabase.databaseWriteExecutor;
    }

    public static synchronized NoteManager getInstance(Context context) {
        if (instance == null) {
            instance = new NoteManager(context);
        }
        return instance;
    }

    // addNote now returns void. Caller should not expect immediate Note object with ID.
    public void addNote(String title, String content, long notebookId) {
        // Use the constructor that Room ignores for new entities
        Note newNote = new Note(title, content, notebookId);
        databaseWriteExecutor.execute(() -> noteDao.insert(newNote));
    }

    public void addNote(String title, String content) {
        addNote(title, content, Note.UNASSIGNED_NOTEBOOK_ID);
    }

    public Note getNoteById(long id) {
        try {
            return databaseWriteExecutor.submit(() -> noteDao.getNoteById(id)).get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public List<Note> getAllNotes() {
        try {
            return databaseWriteExecutor.submit(() -> noteDao.getAllNotes()).get();
        } catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        }
    }

    public boolean updateNote(long id, String newTitle, String newContent, long newNotebookId) {
        try {
            return databaseWriteExecutor.submit(() -> {
                Note noteToUpdate = noteDao.getNoteById(id);
                if (noteToUpdate != null) {
                    // Check if targetNotebookId is valid (exists in NotebookManager) or UNASSIGNED_NOTEBOOK_ID
                    // This check should ideally be done before submitting to executor or handled carefully
                    // For now, assuming newNotebookId is validated by caller or a simpler check
                    NotebookManager notebookManager = NotebookManager.getInstance(null); // PROBLEM: Needs context!
                                                                                      // This shows direct dependency issues.
                                                                                      // For now, we will assume this check might be simplified
                                                                                      // or the NotebookManager call is removed from here.
                                                                                      // Let's remove it for now, DAO should ensure FK if possible,
                                                                                      // or service layer handles this.
                    // boolean notebookIsValid = newNotebookId == Note.UNASSIGNED_NOTEBOOK_ID ||
                    //                            notebookManager.getNotebookById(newNotebookId) != null;
                    // if (!notebookIsValid) {
                    //     return false;
                    // }

                    noteToUpdate.setTitle(newTitle);
                    noteToUpdate.setContent(newContent);
                    noteToUpdate.setNotebookId(newNotebookId);
                    noteToUpdate.setLastModifiedDate(new Date().getTime()); // Explicitly set last modified date
                    noteDao.update(noteToUpdate);
                    return true;
                }
                return false;
            }).get();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public boolean deleteNote(long id) {
        try {
            return databaseWriteExecutor.submit(() -> {
                Note noteToDelete = noteDao.getNoteById(id); // Fetch first to ensure it exists
                if (noteToDelete != null) {
                    return noteDao.delete(noteToDelete) > 0; // delete returns int (rows affected)
                }
                return false;
            }).get();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public List<Note> getNotesByNotebook(long notebookId) {
        try {
            return databaseWriteExecutor.submit(() -> noteDao.getNotesByNotebookId(notebookId)).get();
        } catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        }
    }

    public List<Note> getUnassignedNotes() {
        try {
            return databaseWriteExecutor.submit(() -> noteDao.getUnassignedNotes(Note.UNASSIGNED_NOTEBOOK_ID)).get();
        } catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        }
    }

    public boolean moveNoteToNotebook(long noteId, long targetNotebookId) {
        // Consider fetching note and notebook to validate before executing query
        // For now, directly call DAO.
        try {
            databaseWriteExecutor.execute(() -> noteDao.moveNoteToNotebook(noteId, targetNotebookId, System.currentTimeMillis()));
            return true; // Assuming success if execute doesn't throw. A more robust way is needed for confirmation.
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public void handleNotebookDeleted(long deletedNotebookId) {
        databaseWriteExecutor.execute(() -> noteDao.reassignNotesFromDeletedNotebook(deletedNotebookId, Note.UNASSIGNED_NOTEBOOK_ID, System.currentTimeMillis()));
    }
}
