package com.example.androidnotebook;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.Date;
import java.util.Objects;

@Entity(tableName = "notes")
public class Note {
    @PrimaryKey(autoGenerate = true)
    private long id;

    @ColumnInfo(name = "title")
    private String title;

    @ColumnInfo(name = "content")
    private String content;

    @ColumnInfo(name = "creation_date")
    private long creationDate;

    @ColumnInfo(name = "last_modified_date")
    private long lastModifiedDate;

    @ColumnInfo(name = "notebook_id")
    private long notebookId;

    public static final long UNASSIGNED_NOTEBOOK_ID = 0;

    // Constructor for Room (all fields)
    public Note(long id, String title, String content, long creationDate, long lastModifiedDate, long notebookId) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.creationDate = creationDate;
        this.lastModifiedDate = lastModifiedDate;
        this.notebookId = notebookId;
    }

    // Constructor for creating new notes (id is auto-generated by Room, timestamps are set automatically)
    @Ignore // Room should ignore this constructor for creating instances from DB
    public Note(String title, String content, long notebookId) {
        this.title = title;
        this.content = content;
        this.notebookId = notebookId;
        this.creationDate = new Date().getTime();
        this.lastModifiedDate = this.creationDate;
        // id will be 0, Room will generate it
    }

    @Ignore
    public Note(long id, String title, String content, long notebookId) { // Keep this for NoteManager compatibility for now
        this.id = id; // This id might be problematic if it's not 0 for new notes.
        this.title = title;
        this.content = content;
        this.notebookId = notebookId;
        this.creationDate = new Date().getTime();
        this.lastModifiedDate = this.creationDate;
    }


    @Ignore // Keep this for NoteManager compatibility for now
    public Note(long id, String title, String content) {
        this(id, title, content, UNASSIGNED_NOTEBOOK_ID);
    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
        this.lastModifiedDate = new Date().getTime();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
        this.lastModifiedDate = new Date().getTime();
    }

    public long getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(long creationDate) {
        this.creationDate = creationDate;
    }

    public long getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(long lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public long getNotebookId() {
        return notebookId;
    }

    public void setNotebookId(long notebookId) {
        this.notebookId = notebookId;
        this.lastModifiedDate = new Date().getTime(); // Update lastModifiedDate
    }

    @Override
    public String toString() {
        return "Note{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", creationDate=" + creationDate +
                ", lastModifiedDate=" + lastModifiedDate +
                ", notebookId=" + notebookId + // Added to toString
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Note note = (Note) o;
        return id == note.id &&
                creationDate == note.creationDate &&
                lastModifiedDate == note.lastModifiedDate &&
                notebookId == note.notebookId && // Added to equals
                Objects.equals(title, note.title) &&
                Objects.equals(content, note.content);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, content, creationDate, lastModifiedDate, notebookId); // Added to hashCode
    }
}
