package com.example.androidnotebook;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.Date;
import java.util.Objects;

@Entity(tableName = "notebooks")
public class Notebook {
    @PrimaryKey(autoGenerate = true)
    private long id;

    @ColumnInfo(name = "name")
    private String name;

    @ColumnInfo(name = "creation_date")
    private long creationDate;

    // Constructor for Room
    public Notebook(long id, String name, long creationDate) {
        this.id = id;
        this.name = name;
        this.creationDate = creationDate;
    }

    // Constructor for creating new notebooks (id is auto-generated by Room)
    @Ignore // Room should ignore this constructor
    public Notebook(String name) {
        this.name = name;
        this.creationDate = new Date().getTime();
        // id will be 0, Room will generate it
    }

    @Ignore // Keep for NotebookManager compatibility for now
    public Notebook(long id, String name) {
        this.id = id;
        this.name = name;
        this.creationDate = new Date().getTime();
    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        // Potentially update a lastModifiedDate if we add one for notebooks
    }

    public long getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(long creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public String toString() {
        return "Notebook{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", creationDate=" + creationDate +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Notebook notebook = (Notebook) o;
        return id == notebook.id &&
                creationDate == notebook.creationDate &&
                Objects.equals(name, notebook.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, creationDate);
    }
}
